version: '3.9'
services:
  app:
    build: ./
    command: npm run dev
    ports:
      - 5000:5000
    environment:
      PORT: 5000
    volumes:
      - ./:/src/
      - nodemodules:/src/node_modules

volumes:
  nodemodules: {}
